stages:
  - docker-build-before
  - docker-build
  - merge-manifests

docker-build-before:
  stage: docker-build-before
  image: python:latest
  script:
    - pip install requests
    - python tags.py
    - ls
    - cat tags.sh
    - cat tool.sh
  artifacts:
    paths:
      - tags.sh
      - tool.sh

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  needs:
    - job: docker-build-before
      artifacts: true
  script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - ls
    - chmod +x tags.sh
    - ./tags.sh
  artifacts:
    paths:
      - tool.sh

merge-manifests:
  stage: merge-manifests
  needs:
    - job: docker-build
      artifacts: true
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [ "" ]
  script:
    - manifest-tool --help
    - manifest-tool push --help
    - manifest-tool push from-args --help
    - chmod +x tool.sh
    - ./tool.sh
