stages:
  - docker-build
  - merge-manifests

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  variables:
    EXECUTOR_ARCHITECTURES: amd64 arm64 s390x ppc64le
    EXECUTOR_DEBUG_ARCHITECTURES: amd64 arm64 s390x
    EXECUTOR_SLIM_ARCHITECTURES: amd64 arm64 s390x ppc64le
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - |
      for platform in $EXECUTOR_ARCHITECTURES; do
        docker pull --platform=linux/$platform gcr.io/kaniko-project/executor:latest && docker tag gcr.io/kaniko-project/executor:latest $DOCKER_USERNAME/kaniko-project-executor:latest-$platform || echo "不存在：gcr.io/kaniko-project/executor:latest";
        docker push $DOCKER_USERNAME/kaniko-project-executor:latest-$platform || echo "不存在：$DOCKER_USERNAME/kaniko-project-executor:latest-$platform";
      done
    - |
      for platform in $EXECUTOR_DEBUG_ARCHITECTURES; do
        docker pull --platform=linux/$platform gcr.io/kaniko-project/executor:debug && docker tag gcr.io/kaniko-project/executor:debug $DOCKER_USERNAME/kaniko-project-executor:debug-$platform || echo "不存在：gcr.io/kaniko-project/executor:debug";
        docker push $DOCKER_USERNAME/kaniko-project-executor:debug-$platform || echo "不存在：$DOCKER_USERNAME/kaniko-project-executor:debug-$platform";
      done
    - |
      for platform in $EXECUTOR_SLIM_ARCHITECTURES; do
        docker pull --platform=linux/$platform gcr.io/kaniko-project/executor:slim && docker tag gcr.io/kaniko-project/executor:slim $DOCKER_USERNAME/kaniko-project-executor:slim-$platform || echo "不存在：gcr.io/kaniko-project/executor:slim";
        docker push $DOCKER_USERNAME/kaniko-project-executor:slim-$platform || echo "不存在：$DOCKER_USERNAME/kaniko-project-executor:slim-$platform";
      done

merge-manifests:
  stage: merge-manifests
  needs:
    - job: docker-build
      artifacts: true
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [ "" ]
  variables:
    EXECUTOR_ARCHITECTURES: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
    EXECUTOR_DEBUG_ARCHITECTURES: linux/amd64,linux/arm64,linux/s390x
    EXECUTOR_SLIM_ARCHITECTURES: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  script:
    - manifest-tool --help
    - manifest-tool push --help
    - manifest-tool push from-args --help
    - manifest-tool --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD push from-args --platforms $EXECUTOR_ARCHITECTURES       --template $DOCKER_USERNAME/kaniko-project-executor:latest-ARCH --target $DOCKER_USERNAME/kaniko-project-executor:latest --ignore-missing || echo "无法合并 $DOCKER_USERNAME/kaniko-project-executor:latest-ARCH"
    - manifest-tool --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD push from-args --platforms $EXECUTOR_DEBUG_ARCHITECTURES --template $DOCKER_USERNAME/kaniko-project-executor:debug-ARCH  --target $DOCKER_USERNAME/kaniko-project-executor:debug  --ignore-missing || echo "无法合并 $DOCKER_USERNAME/kaniko-project-executor:debug-ARCH"
    - manifest-tool --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD push from-args --platforms $EXECUTOR_SLIM_ARCHITECTURES  --template $DOCKER_USERNAME/kaniko-project-executor:slim-ARCH   --target $DOCKER_USERNAME/kaniko-project-executor:slim   --ignore-missing || echo "无法合并 $DOCKER_USERNAME/kaniko-project-executor:slim-ARCH"
